import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { logout } from "@/libs/action"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Link href="/">home</Link>
        <Link href="/login">login</Link>
        <Link href="/register">register</Link>
        <Link href="/dashboard">DashBoard</Link>
        <form action={logout}>
          <button>로그아웃</button>
        </form>
        {children}
      </body>
    </html>
  )
}
